const decks = {
  studieteknik:['Studieteknik för teknikelever|The Science of Learning – studera på sätt som bygger kunskap som håller.','Mål|Du ska kunna träna aktivt, planera repetition och välja nästa steg när du fastnar.','Känna igen är inte samma sak som kunna|Att en text känns bekant betyder inte att du kan förklara eller använda kunskapen utan stöd.','Hämta fram|Läs först kort. Stäng sedan materialet och förklara, rita eller lös uppgiften utan att titta.','Sprid ut repetition|Träna i dag, repetera om två dagar, gör en blandad uppgift efter en vecka och återkom igen.','Blanda när grunden finns|Blanda exempelvis procent, enheter och ekvationer. Då måste du välja metod själv.','Minska belastningen|När något är nytt: använd ett genomarbetat exempel, en idé i taget och tydliga steg.','Använd fel|Ett fel kan bero på en missförstådd fråga, fel metod, räknefel eller glömd enhet. Ta reda på vilket.','Metakognition|Före: vad kan jag? Under: vad är oklart? Efter: vad ska jag repetera och när?','Prova själv|Gör en 25-minuterscykel: mål, exempel, två egna uppgifter, rättning och repetitionsplan.','Exit ticket|Vilken strategi ska du använda redan vid nästa studiepass?'],
  'matte-tal':['Tal, procent och enheter|Repetition inför teknikprogrammet.','Mål|Växla mellan bråk, decimalform och procent. Omvandla enheter.','Samma värde – olika form|1/4 = 0,25 = 25 %.','Procent|25 % av 800 kr är 0,25 × 800 = 200 kr.','Enheter|1,8 m = 180 cm. Skriv alltid ut enheten.','Prova själv|Hur mycket är 15 % av 200? Förklara ditt sätt.','Exit ticket|När behöver du göra en rimlighetskontroll?'],
  'matte-algebra':['Algebra och formler|Variabler gör att samband kan beskrivas kort.','Mål|Lösa ekvationer och använda formler med rätt enheter.','Ekvationer|Gör samma sak på båda sidor. 3x + 4 = 19 → x = 5.','Formler|Skriv storhet och enhet före beräkningen. v = s / t.','Prova själv|En sträcka är 300 m och tiden 60 s. Beräkna hastigheten.','Exit ticket|Vilket steg brukar du behöva kontrollera extra noga?'],
  'matte-grafer':['Grafer och geometri|Se samband, förändring och mått.','Mål|Läsa grafer samt beräkna area och volym.','Grafer|Läs axlar, enheter och lutning innan du räknar.','Geometri|Area = längd × bredd. Svara i kvadratenheter.','Prova själv|En rektangel är 5 m × 3 m. Vad är arean?','Exit ticket|Vad betyder lutningen i en sträcka–tid-graf?'],
  fysik:['Fysik från grundskolan|Rörelse, krafter, energi och elektricitet.','Mål|Använd storheter och enheter samt tolka enkla samband.','Rörelse|Hastighet = sträcka / tid. Enhet: m/s.','Krafter|Rita krafter som pilar. Tyngdkraften verkar mot jordens centrum.','Elektricitet|Ström mäts i A, spänning i V och resistans i Ω.','Prova själv|100 m på 20 s. Beräkna hastigheten.','Exit ticket|Vilken enhet ska stå i ditt svar?'],
  kemi:['Kemi från grundskolan|Materia, reaktioner och material.','Mål|Förstå atom, molekyl, jon och grundläggande formler.','Partiklar|Grundämnen består av en sorts atomer.','Formler|H₂O: två väteatomer och en syreatom.','Kemi i teknik|Materialens egenskaper påverkar konstruktion, batterier och återvinning.','Prova själv|Vilket grundämne har symbolen O?','Exit ticket|Vad är skillnaden mellan atom och molekyl?'],
  svenska:['Svenska i teknikämnen|Läs vad frågan ber om och gör ditt resonemang tydligt.','Mål|Förstå uppmaningar och skriva med tydliga ämnesord.','Läs strategiskt|Markera: beräkna, förklara, jämför eller resonera.','Skriv tydligt|Använd eftersom, därför och till exempel.','Prova själv|Skriv en mening som förklarar varför en resistor blir varm.','Exit ticket|Vilket verb står i nästa uppgift du får?'],
  engelska:['Engelska för teknikstudier|Förstå instruktioner och centrala begrepp.','Mål|Använd vanliga instruktioner och läs med stöd av sammanhang.','Nyckelverb|calculate = beräkna, measure = mät, compare = jämför.','Läs med stöd|Titta på rubrik, bild och nyckelord först.','Prova själv|Översätt: Measure the voltage.','Exit ticket|Vilket nytt engelskt ord behöver du repetera?'],
  digitalt:['Digital grundkompetens|Ordning, dokument och säkerhet.','Mål|Hantera filer och skydda dina konton.','Filstruktur|Datum_uppgift_version gör filer enkla att hitta.','Säkerhet|Använd långt, unikt lösenord och tvåfaktorsautentisering.','Prova själv|Skapa en mappstruktur för en fysiklaboration.','Exit ticket|Var sparar du din säkra kopia?']
};
const chapter = new URLSearchParams(location.search).get('chapter') || 'studieteknik'; const slides=(decks[chapter]||decks.studieteknik).map(item=>item.split('|')); let current=0;
function render(){ const [title,text]=slides[current]; document.querySelector('#slide').innerHTML=`<p class="eyebrow">Förkunskaper för teknik · Presentation</p><h1>${title}</h1><p class="slide-text">${text}</p>`; document.querySelector('#slide-count').textContent=`Bild ${current+1} av ${slides.length}`; document.querySelector('#previous').disabled=current===0; document.querySelector('#next').disabled=current===slides.length-1; }
document.addEventListener('DOMContentLoaded',()=>{render(); document.querySelector('#previous').onclick=()=>{current--;render()}; document.querySelector('#next').onclick=()=>{current++;render()}; document.addEventListener('keydown',e=>{if(e.key==='ArrowRight'&&current<slides.length){current++;render()} if(e.key==='ArrowLeft'&&current>0){current--;render()}});});
